name: 'Batman'
branding:
  icon: 'message-circle'  
  color: 'blue'
description: 'Make GitHub Batman one innocent people.'
author: 'Jono Allen'
inputs: 
  percentage:
    description: 'How many people out of hundred should be Batmaned (set this to 100 if you want to Batmaned everyone)'
    required: true
  message:
    description: 'Comment message when not Batmaning (Optional : No comment would be made if not provided)'
    required: false
    default: ''
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: true
  GITHUB_AUTHOR_ID:
    description: 'github author to Batmaned'
    required: true
runs:
  using: 'node12'
  main: 'index.js'